# Generated by Django 4.2.25 on 2025-11-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
